# Generated by Django 3.2.8 on 2021-10-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True)),
                ('user_id', models.CharField(max_length=32)),
                ('weight', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'measurement',
            },
        ),
    ]
